language: ruby

rvm:
  - 1.9.3

before_script:
  - psql -c 'create database hamster_test;' -U postgres

env:
  - DB=postgres

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
    
notifications:
  email:
    - crew@geeksoflondon.com
