development:
    adapter: postgresql
    database: hamster
    host: localhost
    encoding: UTF8

test:
    adapter: postgresql
    database: hamster_test
    username:
    encoding: UTF8
    min_messages: WARNING

postgres:
  adapter: postgresql
  database: hamster_test
  username: postgres